### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [twitter/flockdb#103]
Hi there, 

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. **FlockDB** was in my list. However, I observed that the software history of when the software was developed as a proprietary software was not kept after the transition to Github.

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask **FlockDB** developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the _core developers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the _newcomers_ faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by stuhood** [comment]
The history was kept. What makes you think it wasn't?

**Comment by gustavopinto** [comment]
Hi @stuhood, 

it seems that the first commit uploaded all existing code at once (5K additions):

https://github.com/twitter/flockdb/commit/9486041029c89f4b8c4daeb21eec5cb7c80efed0

Was this code maintained elsewhere and was pushed in a single commit to Github, or was it wrote without any control version system?

Thanks again,

Gustavo

**Comment by gustavopinto** [comment]
Hi @stuhood, any comment on this issue?

**Comment by stuhood** [comment]
AFAIK, that was the initial commit to the project. To get more information you'd need to talk directly to the first committer.
